#!/bin/bash
if [ $1 == "-r" ]; then
  yum info kernel-devel 2>/dev/null | awk '/^Arch/{ARCH=$3}/^Version/{VER=$3}/^Release/{REL=$3}END{print VER "-" REL "." ARCH}'
else
  exec /usr/bin/uname.org $*
fi
