name: CI
on:
  push:
    tags: [ '*' ]
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - target: drbd9-rpm
           dockerfile: Dockerfile
         - target: drbd9-rpm-amzn2
           dockerfile: Dockerfile.amzn2
         - target: drbd9-rpm-foros8
           dockerfile: Dockerfile.foros8
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          TRAVIS_BUILD_DIR: ${{ github.workspace }}
          TARGET: ${{ matrix.target }}
          DOCKERFILE: ${{ matrix.dockerfile }}
        run: |
          docker build -t procube/$TARGET -f $DOCKERFILE .
          mkdir -p /tmp/RPMS/{x86_64,noarch}
          sudo chown 111:111 -R /tmp/RPMS
          docker run --rm --privileged --name drbd9-rpm -v /tmp/RPMS:/home/builder/rpmbuild/RPMS procube/$TARGET
          (cd /tmp;tar -czf - RPMS) > $TRAVIS_BUILD_DIR/$TARGET.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
