name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         # kernel revision of almalinux is fixed at 4.18.0-425.3.1.el8 in all minor version
         # so, use 8.7
         - dockerfile: Dockerfile.foros8
           drbd_tag: drbd-9.2.7
           util_tag: v9.27.0
           image_tag: 8.9
         - dockerfile: Dockerfile.foros8
           drbd_tag: drbd-9.2.4
           util_tag: v9.24.0
           image_tag: 8.8
         - dockerfile: Dockerfile.foros8
           drbd_tag: drbd-9.1.15
           util_tag: v9.22.0
           image_tag: 8.8
         - dockerfile: Dockerfile.foros9
           drbd_tag: drbd-9.2.4
           util_tag: v9.24.0
           image_tag: 9.2
         - dockerfile: Dockerfile.foros9
           drbd_tag: drbd-9.1.15
           util_tag: v9.22.0
           image_tag: 9.2
         - dockerfile: Dockerfile.foros9
           drbd_tag: drbd-9.2.7
           util_tag: v9.27.0
           image_tag: 9.4
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          BUILD_DIR: ${{ github.workspace }}
          DOCKERFILE: ${{ matrix.dockerfile }}
          IMAGE_TAG: ${{ matrix.image_tag }}
          DRBD_TAG: ${{ matrix.drbd_tag }}
          UTIL_TAG: ${{ matrix.util_tag }}
        run: |
          mkdir $BUILD_DIR/build
          docker build -t builder -f $DOCKERFILE . --build-arg DRBD_TAG=$DRBD_TAG --build-arg UTIL_TAG=$UTIL_TAG --build-arg IMAGE_TAG=$IMAGE_TAG
          docker run --rm --privileged -v RPMS:/home/builder/rpmbuild/RPMS builder
          docker run --rm -v RPMS:/home/builder/rpmbuild/RPMS builder tar -cz -C /home/builder/rpmbuild RPMS > $BUILD_DIR/build/$(docker run --rm builder /bin/bash version.sh).tar.gz
          docker volume rm RPMS
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Latests
          tag_name: Latests
          files: 'build/*.tar.gz'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
